<?php


/**
 * This class adds structure of 'rise_article' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 24 23:50:29 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RiseArticleMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RiseArticleMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(RiseArticlePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(RiseArticlePeer::TABLE_NAME);
		$tMap->setPhpName('RiseArticle');
		$tMap->setClassname('RiseArticle');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('CATEGORY_ID', 'CategoryId', 'INTEGER', 'rise_category', 'ID', true, null);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', true, 255);

		$tMap->addColumn('IMAGE', 'Image', 'VARCHAR', false, 255);

		$tMap->addColumn('SHORT', 'Short', 'VARCHAR', false, 255);

		$tMap->addColumn('CONTENT', 'Content', 'LONGVARCHAR', true, null);

		$tMap->addColumn('AUTHOR', 'Author', 'VARCHAR', true, 255);

		$tMap->addColumn('IS_MAIN_OF_CATEGORY', 'IsMainOfCategory', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_MAIN_OF_DAY', 'IsMainOfDay', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_NEWS', 'IsNews', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_PUBLIC', 'IsPublic', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_INTRASH', 'IsIntrash', 'BOOLEAN', true, null);

		$tMap->addColumn('TOKEN', 'Token', 'VARCHAR', true, 255);

		$tMap->addColumn('ROOT', 'Root', 'VARCHAR', false, 255);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // RiseArticleMapBuilder
