<?php

/**
 * Base class that represents a row from the 'rise_article' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 24 23:50:29 2009
 *
 * @package    lib.model.om
 */
abstract class BaseRiseArticle extends BaseObject  implements Persistent {


  const PEER = 'RiseArticlePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RiseArticlePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * The value for the short field.
	 * @var        string
	 */
	protected $short;

	/**
	 * The value for the content field.
	 * @var        string
	 */
	protected $content;

	/**
	 * The value for the author field.
	 * @var        string
	 */
	protected $author;

	/**
	 * The value for the is_main_of_category field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_main_of_category;

	/**
	 * The value for the is_main_of_day field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_main_of_day;

	/**
	 * The value for the is_news field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_news;

	/**
	 * The value for the is_public field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_public;

	/**
	 * The value for the is_intrash field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_intrash;

	/**
	 * The value for the token field.
	 * @var        string
	 */
	protected $token;

	/**
	 * The value for the root field.
	 * @var        string
	 */
	protected $root;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        RiseCategory
	 */
	protected $aRiseCategory;

	/**
	 * @var        array RiseMenuItem[] Collection to store aggregation of RiseMenuItem objects.
	 */
	protected $collRiseMenuItems;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRiseMenuItems.
	 */
	private $lastRiseMenuItemCriteria = null;

	/**
	 * @var        array RiseComment[] Collection to store aggregation of RiseComment objects.
	 */
	protected $collRiseComments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRiseComments.
	 */
	private $lastRiseCommentCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRiseArticle object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_main_of_category = false;
		$this->is_main_of_day = false;
		$this->is_news = false;
		$this->is_public = false;
		$this->is_intrash = false;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Get the [short] column value.
	 * 
	 * @return     string
	 */
	public function getShort()
	{
		return $this->short;
	}

	/**
	 * Get the [content] column value.
	 * 
	 * @return     string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get the [author] column value.
	 * 
	 * @return     string
	 */
	public function getAuthor()
	{
		return $this->author;
	}

	/**
	 * Get the [is_main_of_category] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsMainOfCategory()
	{
		return $this->is_main_of_category;
	}

	/**
	 * Get the [is_main_of_day] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsMainOfDay()
	{
		return $this->is_main_of_day;
	}

	/**
	 * Get the [is_news] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsNews()
	{
		return $this->is_news;
	}

	/**
	 * Get the [is_public] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsPublic()
	{
		return $this->is_public;
	}

	/**
	 * Get the [is_intrash] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsIntrash()
	{
		return $this->is_intrash;
	}

	/**
	 * Get the [token] column value.
	 * 
	 * @return     string
	 */
	public function getToken()
	{
		return $this->token;
	}

	/**
	 * Get the [root] column value.
	 * 
	 * @return     string
	 */
	public function getRoot()
	{
		return $this->root;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RiseArticlePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = RiseArticlePeer::CATEGORY_ID;
		}

		if ($this->aRiseCategory !== null && $this->aRiseCategory->getId() !== $v) {
			$this->aRiseCategory = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = RiseArticlePeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = RiseArticlePeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Set the value of [short] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setShort($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->short !== $v) {
			$this->short = $v;
			$this->modifiedColumns[] = RiseArticlePeer::SHORT;
		}

		return $this;
	} // setShort()

	/**
	 * Set the value of [content] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setContent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->content !== $v) {
			$this->content = $v;
			$this->modifiedColumns[] = RiseArticlePeer::CONTENT;
		}

		return $this;
	} // setContent()

	/**
	 * Set the value of [author] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setAuthor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->author !== $v) {
			$this->author = $v;
			$this->modifiedColumns[] = RiseArticlePeer::AUTHOR;
		}

		return $this;
	} // setAuthor()

	/**
	 * Set the value of [is_main_of_category] column.
	 * 
	 * @param      boolean $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setIsMainOfCategory($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_main_of_category !== $v || $v === false) {
			$this->is_main_of_category = $v;
			$this->modifiedColumns[] = RiseArticlePeer::IS_MAIN_OF_CATEGORY;
		}

		return $this;
	} // setIsMainOfCategory()

	/**
	 * Set the value of [is_main_of_day] column.
	 * 
	 * @param      boolean $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setIsMainOfDay($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_main_of_day !== $v || $v === false) {
			$this->is_main_of_day = $v;
			$this->modifiedColumns[] = RiseArticlePeer::IS_MAIN_OF_DAY;
		}

		return $this;
	} // setIsMainOfDay()

	/**
	 * Set the value of [is_news] column.
	 * 
	 * @param      boolean $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setIsNews($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_news !== $v || $v === false) {
			$this->is_news = $v;
			$this->modifiedColumns[] = RiseArticlePeer::IS_NEWS;
		}

		return $this;
	} // setIsNews()

	/**
	 * Set the value of [is_public] column.
	 * 
	 * @param      boolean $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setIsPublic($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_public !== $v || $v === false) {
			$this->is_public = $v;
			$this->modifiedColumns[] = RiseArticlePeer::IS_PUBLIC;
		}

		return $this;
	} // setIsPublic()

	/**
	 * Set the value of [is_intrash] column.
	 * 
	 * @param      boolean $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setIsIntrash($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_intrash !== $v || $v === false) {
			$this->is_intrash = $v;
			$this->modifiedColumns[] = RiseArticlePeer::IS_INTRASH;
		}

		return $this;
	} // setIsIntrash()

	/**
	 * Set the value of [token] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setToken($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->token !== $v) {
			$this->token = $v;
			$this->modifiedColumns[] = RiseArticlePeer::TOKEN;
		}

		return $this;
	} // setToken()

	/**
	 * Set the value of [root] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setRoot($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->root !== $v) {
			$this->root = $v;
			$this->modifiedColumns[] = RiseArticlePeer::ROOT;
		}

		return $this;
	} // setRoot()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RiseArticlePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RiseArticle The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RiseArticlePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(RiseArticlePeer::IS_MAIN_OF_CATEGORY,RiseArticlePeer::IS_MAIN_OF_DAY,RiseArticlePeer::IS_NEWS,RiseArticlePeer::IS_PUBLIC,RiseArticlePeer::IS_INTRASH))) {
				return false;
			}

			if ($this->is_main_of_category !== false) {
				return false;
			}

			if ($this->is_main_of_day !== false) {
				return false;
			}

			if ($this->is_news !== false) {
				return false;
			}

			if ($this->is_public !== false) {
				return false;
			}

			if ($this->is_intrash !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->category_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->title = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->image = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->short = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->content = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->author = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->is_main_of_category = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->is_main_of_day = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->is_news = ($row[$startcol + 9] !== null) ? (boolean) $row[$startcol + 9] : null;
			$this->is_public = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->is_intrash = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->token = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->root = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->created_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->updated_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = RiseArticlePeer::NUM_COLUMNS - RiseArticlePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RiseArticle object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aRiseCategory !== null && $this->category_id !== $this->aRiseCategory->getId()) {
			$this->aRiseCategory = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RiseArticlePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RiseArticlePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aRiseCategory = null;
			$this->collRiseMenuItems = null;
			$this->lastRiseMenuItemCriteria = null;

			$this->collRiseComments = null;
			$this->lastRiseCommentCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRiseArticle:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RiseArticlePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RiseArticlePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRiseArticle:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRiseArticle:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(RiseArticlePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(RiseArticlePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RiseArticlePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRiseArticle:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RiseArticlePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRiseCategory !== null) {
				if ($this->aRiseCategory->isModified() || $this->aRiseCategory->isNew()) {
					$affectedRows += $this->aRiseCategory->save($con);
				}
				$this->setRiseCategory($this->aRiseCategory);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RiseArticlePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RiseArticlePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RiseArticlePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collRiseMenuItems !== null) {
				foreach ($this->collRiseMenuItems as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRiseComments !== null) {
				foreach ($this->collRiseComments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRiseCategory !== null) {
				if (!$this->aRiseCategory->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRiseCategory->getValidationFailures());
				}
			}


			if (($retval = RiseArticlePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collRiseMenuItems !== null) {
					foreach ($this->collRiseMenuItems as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRiseComments !== null) {
					foreach ($this->collRiseComments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RiseArticlePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCategoryId();
				break;
			case 2:
				return $this->getTitle();
				break;
			case 3:
				return $this->getImage();
				break;
			case 4:
				return $this->getShort();
				break;
			case 5:
				return $this->getContent();
				break;
			case 6:
				return $this->getAuthor();
				break;
			case 7:
				return $this->getIsMainOfCategory();
				break;
			case 8:
				return $this->getIsMainOfDay();
				break;
			case 9:
				return $this->getIsNews();
				break;
			case 10:
				return $this->getIsPublic();
				break;
			case 11:
				return $this->getIsIntrash();
				break;
			case 12:
				return $this->getToken();
				break;
			case 13:
				return $this->getRoot();
				break;
			case 14:
				return $this->getCreatedAt();
				break;
			case 15:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RiseArticlePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCategoryId(),
			$keys[2] => $this->getTitle(),
			$keys[3] => $this->getImage(),
			$keys[4] => $this->getShort(),
			$keys[5] => $this->getContent(),
			$keys[6] => $this->getAuthor(),
			$keys[7] => $this->getIsMainOfCategory(),
			$keys[8] => $this->getIsMainOfDay(),
			$keys[9] => $this->getIsNews(),
			$keys[10] => $this->getIsPublic(),
			$keys[11] => $this->getIsIntrash(),
			$keys[12] => $this->getToken(),
			$keys[13] => $this->getRoot(),
			$keys[14] => $this->getCreatedAt(),
			$keys[15] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RiseArticlePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCategoryId($value);
				break;
			case 2:
				$this->setTitle($value);
				break;
			case 3:
				$this->setImage($value);
				break;
			case 4:
				$this->setShort($value);
				break;
			case 5:
				$this->setContent($value);
				break;
			case 6:
				$this->setAuthor($value);
				break;
			case 7:
				$this->setIsMainOfCategory($value);
				break;
			case 8:
				$this->setIsMainOfDay($value);
				break;
			case 9:
				$this->setIsNews($value);
				break;
			case 10:
				$this->setIsPublic($value);
				break;
			case 11:
				$this->setIsIntrash($value);
				break;
			case 12:
				$this->setToken($value);
				break;
			case 13:
				$this->setRoot($value);
				break;
			case 14:
				$this->setCreatedAt($value);
				break;
			case 15:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RiseArticlePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCategoryId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTitle($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setImage($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setShort($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setContent($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setAuthor($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIsMainOfCategory($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIsMainOfDay($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIsNews($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setIsPublic($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setIsIntrash($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setToken($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setRoot($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCreatedAt($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setUpdatedAt($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);

		if ($this->isColumnModified(RiseArticlePeer::ID)) $criteria->add(RiseArticlePeer::ID, $this->id);
		if ($this->isColumnModified(RiseArticlePeer::CATEGORY_ID)) $criteria->add(RiseArticlePeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(RiseArticlePeer::TITLE)) $criteria->add(RiseArticlePeer::TITLE, $this->title);
		if ($this->isColumnModified(RiseArticlePeer::IMAGE)) $criteria->add(RiseArticlePeer::IMAGE, $this->image);
		if ($this->isColumnModified(RiseArticlePeer::SHORT)) $criteria->add(RiseArticlePeer::SHORT, $this->short);
		if ($this->isColumnModified(RiseArticlePeer::CONTENT)) $criteria->add(RiseArticlePeer::CONTENT, $this->content);
		if ($this->isColumnModified(RiseArticlePeer::AUTHOR)) $criteria->add(RiseArticlePeer::AUTHOR, $this->author);
		if ($this->isColumnModified(RiseArticlePeer::IS_MAIN_OF_CATEGORY)) $criteria->add(RiseArticlePeer::IS_MAIN_OF_CATEGORY, $this->is_main_of_category);
		if ($this->isColumnModified(RiseArticlePeer::IS_MAIN_OF_DAY)) $criteria->add(RiseArticlePeer::IS_MAIN_OF_DAY, $this->is_main_of_day);
		if ($this->isColumnModified(RiseArticlePeer::IS_NEWS)) $criteria->add(RiseArticlePeer::IS_NEWS, $this->is_news);
		if ($this->isColumnModified(RiseArticlePeer::IS_PUBLIC)) $criteria->add(RiseArticlePeer::IS_PUBLIC, $this->is_public);
		if ($this->isColumnModified(RiseArticlePeer::IS_INTRASH)) $criteria->add(RiseArticlePeer::IS_INTRASH, $this->is_intrash);
		if ($this->isColumnModified(RiseArticlePeer::TOKEN)) $criteria->add(RiseArticlePeer::TOKEN, $this->token);
		if ($this->isColumnModified(RiseArticlePeer::ROOT)) $criteria->add(RiseArticlePeer::ROOT, $this->root);
		if ($this->isColumnModified(RiseArticlePeer::CREATED_AT)) $criteria->add(RiseArticlePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(RiseArticlePeer::UPDATED_AT)) $criteria->add(RiseArticlePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);

		$criteria->add(RiseArticlePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RiseArticle (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setTitle($this->title);

		$copyObj->setImage($this->image);

		$copyObj->setShort($this->short);

		$copyObj->setContent($this->content);

		$copyObj->setAuthor($this->author);

		$copyObj->setIsMainOfCategory($this->is_main_of_category);

		$copyObj->setIsMainOfDay($this->is_main_of_day);

		$copyObj->setIsNews($this->is_news);

		$copyObj->setIsPublic($this->is_public);

		$copyObj->setIsIntrash($this->is_intrash);

		$copyObj->setToken($this->token);

		$copyObj->setRoot($this->root);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getRiseMenuItems() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRiseMenuItem($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRiseComments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRiseComment($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RiseArticle Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RiseArticlePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RiseArticlePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a RiseCategory object.
	 *
	 * @param      RiseCategory $v
	 * @return     RiseArticle The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRiseCategory(RiseCategory $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aRiseCategory = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RiseCategory object, it will not be re-added.
		if ($v !== null) {
			$v->addRiseArticle($this);
		}

		return $this;
	}


	/**
	 * Get the associated RiseCategory object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RiseCategory The associated RiseCategory object.
	 * @throws     PropelException
	 */
	public function getRiseCategory(PropelPDO $con = null)
	{
		if ($this->aRiseCategory === null && ($this->category_id !== null)) {
			$c = new Criteria(RiseCategoryPeer::DATABASE_NAME);
			$c->add(RiseCategoryPeer::ID, $this->category_id);
			$this->aRiseCategory = RiseCategoryPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRiseCategory->addRiseArticles($this);
			 */
		}
		return $this->aRiseCategory;
	}

	/**
	 * Clears out the collRiseMenuItems collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRiseMenuItems()
	 */
	public function clearRiseMenuItems()
	{
		$this->collRiseMenuItems = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRiseMenuItems collection (array).
	 *
	 * By default this just sets the collRiseMenuItems collection to an empty array (like clearcollRiseMenuItems());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRiseMenuItems()
	{
		$this->collRiseMenuItems = array();
	}

	/**
	 * Gets an array of RiseMenuItem objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RiseArticle has previously been saved, it will retrieve
	 * related RiseMenuItems from storage. If this RiseArticle is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RiseMenuItem[]
	 * @throws     PropelException
	 */
	public function getRiseMenuItems($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRiseMenuItems === null) {
			if ($this->isNew()) {
			   $this->collRiseMenuItems = array();
			} else {

				$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

				RiseMenuItemPeer::addSelectColumns($criteria);
				$this->collRiseMenuItems = RiseMenuItemPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

				RiseMenuItemPeer::addSelectColumns($criteria);
				if (!isset($this->lastRiseMenuItemCriteria) || !$this->lastRiseMenuItemCriteria->equals($criteria)) {
					$this->collRiseMenuItems = RiseMenuItemPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRiseMenuItemCriteria = $criteria;
		return $this->collRiseMenuItems;
	}

	/**
	 * Returns the number of related RiseMenuItem objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RiseMenuItem objects.
	 * @throws     PropelException
	 */
	public function countRiseMenuItems(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRiseMenuItems === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

				$count = RiseMenuItemPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

				if (!isset($this->lastRiseMenuItemCriteria) || !$this->lastRiseMenuItemCriteria->equals($criteria)) {
					$count = RiseMenuItemPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRiseMenuItems);
				}
			} else {
				$count = count($this->collRiseMenuItems);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a RiseMenuItem object to this object
	 * through the RiseMenuItem foreign key attribute.
	 *
	 * @param      RiseMenuItem $l RiseMenuItem
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRiseMenuItem(RiseMenuItem $l)
	{
		if ($this->collRiseMenuItems === null) {
			$this->initRiseMenuItems();
		}
		if (!in_array($l, $this->collRiseMenuItems, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRiseMenuItems, $l);
			$l->setRiseArticle($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RiseArticle is new, it will return
	 * an empty collection; or if this RiseArticle has previously
	 * been saved, it will retrieve related RiseMenuItems from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RiseArticle.
	 */
	public function getRiseMenuItemsJoinRiseMenu($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRiseMenuItems === null) {
			if ($this->isNew()) {
				$this->collRiseMenuItems = array();
			} else {

				$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

				$this->collRiseMenuItems = RiseMenuItemPeer::doSelectJoinRiseMenu($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

			if (!isset($this->lastRiseMenuItemCriteria) || !$this->lastRiseMenuItemCriteria->equals($criteria)) {
				$this->collRiseMenuItems = RiseMenuItemPeer::doSelectJoinRiseMenu($criteria, $con, $join_behavior);
			}
		}
		$this->lastRiseMenuItemCriteria = $criteria;

		return $this->collRiseMenuItems;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RiseArticle is new, it will return
	 * an empty collection; or if this RiseArticle has previously
	 * been saved, it will retrieve related RiseMenuItems from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RiseArticle.
	 */
	public function getRiseMenuItemsJoinRiseCategory($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRiseMenuItems === null) {
			if ($this->isNew()) {
				$this->collRiseMenuItems = array();
			} else {

				$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

				$this->collRiseMenuItems = RiseMenuItemPeer::doSelectJoinRiseCategory($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->id);

			if (!isset($this->lastRiseMenuItemCriteria) || !$this->lastRiseMenuItemCriteria->equals($criteria)) {
				$this->collRiseMenuItems = RiseMenuItemPeer::doSelectJoinRiseCategory($criteria, $con, $join_behavior);
			}
		}
		$this->lastRiseMenuItemCriteria = $criteria;

		return $this->collRiseMenuItems;
	}

	/**
	 * Clears out the collRiseComments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRiseComments()
	 */
	public function clearRiseComments()
	{
		$this->collRiseComments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRiseComments collection (array).
	 *
	 * By default this just sets the collRiseComments collection to an empty array (like clearcollRiseComments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRiseComments()
	{
		$this->collRiseComments = array();
	}

	/**
	 * Gets an array of RiseComment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RiseArticle has previously been saved, it will retrieve
	 * related RiseComments from storage. If this RiseArticle is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RiseComment[]
	 * @throws     PropelException
	 */
	public function getRiseComments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRiseComments === null) {
			if ($this->isNew()) {
			   $this->collRiseComments = array();
			} else {

				$criteria->add(RiseCommentPeer::ARTICLE_ID, $this->id);

				RiseCommentPeer::addSelectColumns($criteria);
				$this->collRiseComments = RiseCommentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RiseCommentPeer::ARTICLE_ID, $this->id);

				RiseCommentPeer::addSelectColumns($criteria);
				if (!isset($this->lastRiseCommentCriteria) || !$this->lastRiseCommentCriteria->equals($criteria)) {
					$this->collRiseComments = RiseCommentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRiseCommentCriteria = $criteria;
		return $this->collRiseComments;
	}

	/**
	 * Returns the number of related RiseComment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RiseComment objects.
	 * @throws     PropelException
	 */
	public function countRiseComments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RiseArticlePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRiseComments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RiseCommentPeer::ARTICLE_ID, $this->id);

				$count = RiseCommentPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RiseCommentPeer::ARTICLE_ID, $this->id);

				if (!isset($this->lastRiseCommentCriteria) || !$this->lastRiseCommentCriteria->equals($criteria)) {
					$count = RiseCommentPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRiseComments);
				}
			} else {
				$count = count($this->collRiseComments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a RiseComment object to this object
	 * through the RiseComment foreign key attribute.
	 *
	 * @param      RiseComment $l RiseComment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRiseComment(RiseComment $l)
	{
		if ($this->collRiseComments === null) {
			$this->initRiseComments();
		}
		if (!in_array($l, $this->collRiseComments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRiseComments, $l);
			$l->setRiseArticle($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collRiseMenuItems) {
				foreach ((array) $this->collRiseMenuItems as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRiseComments) {
				foreach ((array) $this->collRiseComments as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collRiseMenuItems = null;
		$this->collRiseComments = null;
			$this->aRiseCategory = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRiseArticle:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRiseArticle::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRiseArticle
