<?php

/**
 * Base class that represents a row from the 'rise_menu_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 24 23:50:30 2009
 *
 * @package    lib.model.om
 */
abstract class BaseRiseMenuItem extends BaseObject  implements Persistent {


  const PEER = 'RiseMenuItemPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RiseMenuItemPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the menu_id field.
	 * @var        int
	 */
	protected $menu_id;

	/**
	 * The value for the order field.
	 * @var        int
	 */
	protected $order;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the url field.
	 * @var        string
	 */
	protected $url;

	/**
	 * The value for the article_id field.
	 * @var        int
	 */
	protected $article_id;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * @var        RiseMenu
	 */
	protected $aRiseMenu;

	/**
	 * @var        RiseArticle
	 */
	protected $aRiseArticle;

	/**
	 * @var        RiseCategory
	 */
	protected $aRiseCategory;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRiseMenuItem object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [menu_id] column value.
	 * 
	 * @return     int
	 */
	public function getMenuId()
	{
		return $this->menu_id;
	}

	/**
	 * Get the [order] column value.
	 * 
	 * @return     int
	 */
	public function getOrder()
	{
		return $this->order;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [url] column value.
	 * 
	 * @return     string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Get the [article_id] column value.
	 * 
	 * @return     int
	 */
	public function getArticleId()
	{
		return $this->article_id;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [menu_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setMenuId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->menu_id !== $v) {
			$this->menu_id = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::MENU_ID;
		}

		if ($this->aRiseMenu !== null && $this->aRiseMenu->getId() !== $v) {
			$this->aRiseMenu = null;
		}

		return $this;
	} // setMenuId()

	/**
	 * Set the value of [order] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setOrder($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->order !== $v) {
			$this->order = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::ORDER;
		}

		return $this;
	} // setOrder()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [url] column.
	 * 
	 * @param      string $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->url !== $v) {
			$this->url = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::URL;
		}

		return $this;
	} // setUrl()

	/**
	 * Set the value of [article_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setArticleId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->article_id !== $v) {
			$this->article_id = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::ARTICLE_ID;
		}

		if ($this->aRiseArticle !== null && $this->aRiseArticle->getId() !== $v) {
			$this->aRiseArticle = null;
		}

		return $this;
	} // setArticleId()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RiseMenuItem The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = RiseMenuItemPeer::CATEGORY_ID;
		}

		if ($this->aRiseCategory !== null && $this->aRiseCategory->getId() !== $v) {
			$this->aRiseCategory = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->menu_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->order = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->title = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->url = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->article_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->category_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = RiseMenuItemPeer::NUM_COLUMNS - RiseMenuItemPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RiseMenuItem object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aRiseMenu !== null && $this->menu_id !== $this->aRiseMenu->getId()) {
			$this->aRiseMenu = null;
		}
		if ($this->aRiseArticle !== null && $this->article_id !== $this->aRiseArticle->getId()) {
			$this->aRiseArticle = null;
		}
		if ($this->aRiseCategory !== null && $this->category_id !== $this->aRiseCategory->getId()) {
			$this->aRiseCategory = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RiseMenuItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RiseMenuItemPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aRiseMenu = null;
			$this->aRiseArticle = null;
			$this->aRiseCategory = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRiseMenuItem:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RiseMenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RiseMenuItemPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRiseMenuItem:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRiseMenuItem:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RiseMenuItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRiseMenuItem:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RiseMenuItemPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRiseMenu !== null) {
				if ($this->aRiseMenu->isModified() || $this->aRiseMenu->isNew()) {
					$affectedRows += $this->aRiseMenu->save($con);
				}
				$this->setRiseMenu($this->aRiseMenu);
			}

			if ($this->aRiseArticle !== null) {
				if ($this->aRiseArticle->isModified() || $this->aRiseArticle->isNew()) {
					$affectedRows += $this->aRiseArticle->save($con);
				}
				$this->setRiseArticle($this->aRiseArticle);
			}

			if ($this->aRiseCategory !== null) {
				if ($this->aRiseCategory->isModified() || $this->aRiseCategory->isNew()) {
					$affectedRows += $this->aRiseCategory->save($con);
				}
				$this->setRiseCategory($this->aRiseCategory);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RiseMenuItemPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RiseMenuItemPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RiseMenuItemPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRiseMenu !== null) {
				if (!$this->aRiseMenu->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRiseMenu->getValidationFailures());
				}
			}

			if ($this->aRiseArticle !== null) {
				if (!$this->aRiseArticle->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRiseArticle->getValidationFailures());
				}
			}

			if ($this->aRiseCategory !== null) {
				if (!$this->aRiseCategory->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRiseCategory->getValidationFailures());
				}
			}


			if (($retval = RiseMenuItemPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RiseMenuItemPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getMenuId();
				break;
			case 2:
				return $this->getOrder();
				break;
			case 3:
				return $this->getTitle();
				break;
			case 4:
				return $this->getUrl();
				break;
			case 5:
				return $this->getArticleId();
				break;
			case 6:
				return $this->getCategoryId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RiseMenuItemPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getMenuId(),
			$keys[2] => $this->getOrder(),
			$keys[3] => $this->getTitle(),
			$keys[4] => $this->getUrl(),
			$keys[5] => $this->getArticleId(),
			$keys[6] => $this->getCategoryId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RiseMenuItemPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setMenuId($value);
				break;
			case 2:
				$this->setOrder($value);
				break;
			case 3:
				$this->setTitle($value);
				break;
			case 4:
				$this->setUrl($value);
				break;
			case 5:
				$this->setArticleId($value);
				break;
			case 6:
				$this->setCategoryId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RiseMenuItemPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setMenuId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setOrder($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitle($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUrl($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setArticleId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCategoryId($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RiseMenuItemPeer::DATABASE_NAME);

		if ($this->isColumnModified(RiseMenuItemPeer::ID)) $criteria->add(RiseMenuItemPeer::ID, $this->id);
		if ($this->isColumnModified(RiseMenuItemPeer::MENU_ID)) $criteria->add(RiseMenuItemPeer::MENU_ID, $this->menu_id);
		if ($this->isColumnModified(RiseMenuItemPeer::ORDER)) $criteria->add(RiseMenuItemPeer::ORDER, $this->order);
		if ($this->isColumnModified(RiseMenuItemPeer::TITLE)) $criteria->add(RiseMenuItemPeer::TITLE, $this->title);
		if ($this->isColumnModified(RiseMenuItemPeer::URL)) $criteria->add(RiseMenuItemPeer::URL, $this->url);
		if ($this->isColumnModified(RiseMenuItemPeer::ARTICLE_ID)) $criteria->add(RiseMenuItemPeer::ARTICLE_ID, $this->article_id);
		if ($this->isColumnModified(RiseMenuItemPeer::CATEGORY_ID)) $criteria->add(RiseMenuItemPeer::CATEGORY_ID, $this->category_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RiseMenuItemPeer::DATABASE_NAME);

		$criteria->add(RiseMenuItemPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RiseMenuItem (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setMenuId($this->menu_id);

		$copyObj->setOrder($this->order);

		$copyObj->setTitle($this->title);

		$copyObj->setUrl($this->url);

		$copyObj->setArticleId($this->article_id);

		$copyObj->setCategoryId($this->category_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RiseMenuItem Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RiseMenuItemPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RiseMenuItemPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a RiseMenu object.
	 *
	 * @param      RiseMenu $v
	 * @return     RiseMenuItem The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRiseMenu(RiseMenu $v = null)
	{
		if ($v === null) {
			$this->setMenuId(NULL);
		} else {
			$this->setMenuId($v->getId());
		}

		$this->aRiseMenu = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RiseMenu object, it will not be re-added.
		if ($v !== null) {
			$v->addRiseMenuItem($this);
		}

		return $this;
	}


	/**
	 * Get the associated RiseMenu object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RiseMenu The associated RiseMenu object.
	 * @throws     PropelException
	 */
	public function getRiseMenu(PropelPDO $con = null)
	{
		if ($this->aRiseMenu === null && ($this->menu_id !== null)) {
			$c = new Criteria(RiseMenuPeer::DATABASE_NAME);
			$c->add(RiseMenuPeer::ID, $this->menu_id);
			$this->aRiseMenu = RiseMenuPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRiseMenu->addRiseMenuItems($this);
			 */
		}
		return $this->aRiseMenu;
	}

	/**
	 * Declares an association between this object and a RiseArticle object.
	 *
	 * @param      RiseArticle $v
	 * @return     RiseMenuItem The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRiseArticle(RiseArticle $v = null)
	{
		if ($v === null) {
			$this->setArticleId(NULL);
		} else {
			$this->setArticleId($v->getId());
		}

		$this->aRiseArticle = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RiseArticle object, it will not be re-added.
		if ($v !== null) {
			$v->addRiseMenuItem($this);
		}

		return $this;
	}


	/**
	 * Get the associated RiseArticle object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RiseArticle The associated RiseArticle object.
	 * @throws     PropelException
	 */
	public function getRiseArticle(PropelPDO $con = null)
	{
		if ($this->aRiseArticle === null && ($this->article_id !== null)) {
			$c = new Criteria(RiseArticlePeer::DATABASE_NAME);
			$c->add(RiseArticlePeer::ID, $this->article_id);
			$this->aRiseArticle = RiseArticlePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRiseArticle->addRiseMenuItems($this);
			 */
		}
		return $this->aRiseArticle;
	}

	/**
	 * Declares an association between this object and a RiseCategory object.
	 *
	 * @param      RiseCategory $v
	 * @return     RiseMenuItem The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRiseCategory(RiseCategory $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aRiseCategory = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RiseCategory object, it will not be re-added.
		if ($v !== null) {
			$v->addRiseMenuItem($this);
		}

		return $this;
	}


	/**
	 * Get the associated RiseCategory object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RiseCategory The associated RiseCategory object.
	 * @throws     PropelException
	 */
	public function getRiseCategory(PropelPDO $con = null)
	{
		if ($this->aRiseCategory === null && ($this->category_id !== null)) {
			$c = new Criteria(RiseCategoryPeer::DATABASE_NAME);
			$c->add(RiseCategoryPeer::ID, $this->category_id);
			$this->aRiseCategory = RiseCategoryPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRiseCategory->addRiseMenuItems($this);
			 */
		}
		return $this->aRiseCategory;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aRiseMenu = null;
			$this->aRiseArticle = null;
			$this->aRiseCategory = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRiseMenuItem:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRiseMenuItem::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRiseMenuItem
