generator:
  class: sfPropelGenerator
  param:
    model_class:           RiseArticle
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          rise_article
    with_propel_route:     1

    config:
      actions:         ~
      fields:
        title:         { label: Tytuł }
        rise_category: { label: Kategoria }
        category_id:   { label: Kategoria }
        content:       { label: Treść }
        image:         { label: Obrazek }
        is_intrash:    { label: W koszu? }
        root:          { label: Źródło }
        short:         { label: Treść krótka }
        author:        { label: Autor }
        is_news:       { label: News? }
        is_public:     { label: Opublikowany? }
        created_at:    { label: Stworzony }
        expires_at:    { label: Wygasa }
        updated_at:    { label: Ostatnia edycja }
        rise_menu_id:  { label: Nazwa menu }
        menu_generate: { label: Link w menu? }
      list:
        object_actions:
          _edit:          ~
          _delete:        ~
          publish:        ~
          unpublish:      ~
        batch_actions:
          _delete:     ~
          publish:     ~
          unpublish:   ~
        title:         Edycja artykułów
        display:       [=title, rise_category, author, is_news, is_public, is_main_of_day, updated_at]
        sort:          [updated_at, desc]
        max_per_page:  10
      filter:
        display:       [category_id, title, is_public, is_news]
      form:
        display:       ~
      edit:
        title:         Edycja artykułu
      new:
        title:         Nowy artykuł